version: '3.3'

services:
  drupal:
    image: drupal:latest
    ports:
      - 8099:80
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
    restart: always
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=drupal
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    
volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:
  db_data:
  db: 